from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MatrixCase:
    symbol: str
    valence: str
    arg_class: str
    expr: str


MONADIC_PRIMITIVES = {
    "!",
    "+",
    "-",
    "×",
    "÷",
    "⋆",
    "¬",
    "⌽",
    "⍉",
    "≢",
    "↕",
    "⥊",
    "⌊",
    "⌈",
    "|",
    "√",
    "⋈",
    "=",
    "≠",
    "≡",
    "≍",
    "<",
    ">",
    "«",
    "»",
    "⊣",
    "⊢",
    "⊔",
    "∧",
    "∨",
    "⍋",
    "⍒",
    "∊",
    "⊐",
    "⊒",
    "⍷",
    "∾",
    "⊑",
}

DYADIC_PRIMITIVES = {
    "!",
    "+",
    "-",
    "/",
    "<",
    "=",
    ">",
    "|",
    "«",
    "»",
    "×",
    "÷",
    "↑",
    "↓",
    "∊",
    "√",
    "∧",
    "∨",
    "∾",
    "≍",
    "≠",
    "≡",
    "≤",
    "≥",
    "⊏",
    "⊐",
    "⊑",
    "⊒",
    "⊔",
    "⊢",
    "⊣",
    "⋆",
    "⋈",
    "⌈",
    "⌊",
    "⌽",
    "⍉",
    "⍋",
    "⍒",
    "⍷",
    "⥊",
}

MOD1_GLYPHS = {"˙", "˜", "˘", "¨", "⌜", "⁼", "´", "˝", "`"}
MOD2_GLYPHS = {"∘", "○", "⊸", "⟜", "⊘", "◶", "⌾", "⎉", "⚇", "⍟", "⎊"}


PRIMITIVE_MATRIX_CASES = (
    MatrixCase("!", "monadic", "scalar-assert", "! 1"),
    MatrixCase("+", "monadic", "scalar", "+ 3"),
    MatrixCase("-", "monadic", "scalar", "- 3"),
    MatrixCase("×", "monadic", "vector", "× ¯2‿0‿3"),
    MatrixCase("÷", "monadic", "scalar", "÷ 4"),
    MatrixCase("⋆", "monadic", "scalar", "⋆ 1"),
    MatrixCase("¬", "monadic", "vector", "¬ 0‿2‿0"),
    MatrixCase("⌽", "monadic", "vector", "⌽ 1‿2‿3"),
    MatrixCase("⍉", "monadic", "matrix", "⍉ (2‿3 ⥊ ↕6)"),
    MatrixCase("≢", "monadic", "matrix", "≢ (2‿3 ⥊ ↕6)"),
    MatrixCase("↕", "monadic", "scalar", "↕ 5"),
    MatrixCase("⥊", "monadic", "matrix", "⥊ (2‿3 ⥊ ↕6)"),
    MatrixCase("⌊", "monadic", "scalar", "⌊ 1.8"),
    MatrixCase("⌈", "monadic", "scalar", "⌈ 1.2"),
    MatrixCase("|", "monadic", "scalar", "| ¯5"),
    MatrixCase("√", "monadic", "scalar", "√ 9"),
    MatrixCase("⋈", "monadic", "scalar", "⋈ 5"),
    MatrixCase("=", "monadic", "matrix", "= (2‿3 ⥊ ↕6)"),
    MatrixCase("≠", "monadic", "vector", "≠ 10‿20‿30"),
    MatrixCase("≡", "monadic", "boxed", "≡ 1‿(2‿3)"),
    MatrixCase("≍", "monadic", "vector", "≍ 10‿20"),
    MatrixCase("<", "monadic", "scalar", "< 5"),
    MatrixCase(">", "monadic", "boxed", "> ⟨1‿2⋄3‿4⟩"),
    MatrixCase("«", "monadic", "vector", "« 1‿2‿3"),
    MatrixCase("»", "monadic", "vector", "» 1‿2‿3"),
    MatrixCase("⊣", "monadic", "scalar", "⊣ 5"),
    MatrixCase("⊢", "monadic", "scalar", "⊢ 5"),
    MatrixCase("⊔", "monadic", "vector", "⊔ 1‿0‿1‿2"),
    MatrixCase("∧", "monadic", "vector", "∧ 3‿1‿2"),
    MatrixCase("∨", "monadic", "vector", "∨ 3‿1‿2"),
    MatrixCase("⍋", "monadic", "vector", "⍋ 3‿1‿2"),
    MatrixCase("⍒", "monadic", "vector", "⍒ 3‿1‿2"),
    MatrixCase("∊", "monadic", "vector", "∊ 3‿1‿3‿2‿1"),
    MatrixCase("⊐", "monadic", "vector", "⊐ 3‿1‿3‿2‿1"),
    MatrixCase("⊒", "monadic", "vector", "⊒ 3‿1‿3‿2‿1‿3"),
    MatrixCase("⍷", "monadic", "vector", "⍷ 3‿1‿3‿2‿1"),
    MatrixCase("∾", "monadic", "vector", "∾ ⟨1‿2⋄3‿4⟩"),
    MatrixCase("⊑", "monadic", "vector", "⊑ 10‿20‿30"),
    MatrixCase("!", "dyadic", "message-assert", '"ok" ! 1'),
    MatrixCase("+", "dyadic", "scalar-scalar", "2 + 3"),
    MatrixCase("-", "dyadic", "scalar-scalar", "7 - 2"),
    MatrixCase("/", "dyadic", "vector-vector", "1‿0‿2 / 10‿20‿30"),
    MatrixCase("<", "dyadic", "scalar-scalar", "3 < 4"),
    MatrixCase("=", "dyadic", "vector-vector", "1‿2 = 1‿3"),
    MatrixCase(">", "dyadic", "scalar-scalar", "4 > 3"),
    MatrixCase("|", "dyadic", "scalar-scalar", "3 | 10"),
    MatrixCase("«", "dyadic", "scalar-vector", "9 « 1‿2‿3"),
    MatrixCase("»", "dyadic", "scalar-vector", "9 » 1‿2‿3"),
    MatrixCase("×", "dyadic", "scalar-scalar", "6 × 7"),
    MatrixCase("÷", "dyadic", "scalar-scalar", "8 ÷ 2"),
    MatrixCase("↑", "dyadic", "scalar-vector", "2 ↑ 10‿20‿30‿40"),
    MatrixCase("↓", "dyadic", "scalar-vector", "2 ↓ 10‿20‿30‿40"),
    MatrixCase("∊", "dyadic", "vector-vector", "1‿5‿4 ∊ 3‿1‿4"),
    MatrixCase("√", "dyadic", "scalar-scalar", "2 √ 9"),
    MatrixCase("∧", "dyadic", "vector-vector", "1‿0‿2 ∧ 0‿4‿5"),
    MatrixCase("∨", "dyadic", "vector-vector", "1‿0‿0 ∨ 0‿0‿2"),
    MatrixCase("∾", "dyadic", "vector-vector", "1‿2 ∾ 3‿4"),
    MatrixCase("≍", "dyadic", "vector-vector", "1‿2 ≍ 3‿4"),
    MatrixCase("≠", "dyadic", "vector-vector", "1‿2 ≠ 1‿3"),
    MatrixCase("≡", "dyadic", "vector-vector", "1‿2 ≡ 1‿2"),
    MatrixCase("≤", "dyadic", "scalar-scalar", "3 ≤ 4"),
    MatrixCase("≥", "dyadic", "scalar-scalar", "4 ≥ 4"),
    MatrixCase("⊏", "dyadic", "vector-vector", "1‿3 ⊏ 10‿20‿30‿40"),
    MatrixCase("⊐", "dyadic", "vector-vector", "3‿1‿4 ⊐ 1‿5‿4"),
    MatrixCase("⊑", "dyadic", "scalar-vector", "2 ⊑ 10‿20‿30"),
    MatrixCase("⊒", "dyadic", "vector-vector", "3‿1‿3 ⊒ 3‿3‿3"),
    MatrixCase("⊔", "dyadic", "vector-vector", "1‿0‿1‿2 ⊔ 10‿20‿30‿40"),
    MatrixCase("⊢", "dyadic", "scalar-scalar", "1 ⊢ 2"),
    MatrixCase("⊣", "dyadic", "scalar-scalar", "1 ⊣ 2"),
    MatrixCase("⋆", "dyadic", "scalar-scalar", "2 ⋆ 3"),
    MatrixCase("⋈", "dyadic", "scalar-scalar", "1 ⋈ 2"),
    MatrixCase("⌈", "dyadic", "scalar-scalar", "2 ⌈ 5"),
    MatrixCase("⌊", "dyadic", "scalar-scalar", "2 ⌊ 5"),
    MatrixCase("⌽", "dyadic", "scalar-vector", "1 ⌽ 1‿2‿3"),
    MatrixCase("⍉", "dyadic", "vector-matrix", "1‿0 ⍉ (2‿3 ⥊ ↕6)"),
    MatrixCase("⍋", "dyadic", "vector-vector", "2‿4‿6 ⍋ 1‿2‿3‿7"),
    MatrixCase("⍒", "dyadic", "vector-vector", "6‿4‿2 ⍒ 7‿6‿5‿1"),
    MatrixCase("⍷", "dyadic", "vector-vector", "1‿2 ⍷ 0‿1‿2‿1‿2‿3"),
    MatrixCase("⥊", "dyadic", "vector-vector", "2‿3 ⥊ ↕6"),
)

MODIFIER_MATRIX_CASES = (
    MatrixCase("˙", "derived1", "constant", "3˙ 9"),
    MatrixCase("˜", "derived1", "self", "+˜ 3"),
    MatrixCase("˘", "derived1", "cells", "+´˘ (2‿3 ⥊ ↕6)"),
    MatrixCase("¨", "derived1", "each", "-¨ 1‿2‿3"),
    MatrixCase("⌜", "derived1", "table", "1‿2 ({𝕨+𝕩}⌜) 10‿20"),
    MatrixCase("⁼", "derived1", "undo", "2 (+⁼) 5"),
    MatrixCase("´", "derived1", "fold", "+´ 1‿2‿3"),
    MatrixCase("˝", "derived1", "insert", "+˝ 1‿2‿3"),
    MatrixCase("`", "derived1", "scan", "+` 1‿2‿3"),
    MatrixCase("∘", "derived2", "atop", "(-∘×˜) 3"),
    MatrixCase("○", "derived2", "over", "2 (+○|) ¯3"),
    MatrixCase("⊸", "derived2", "before", "2 ({𝕩+1}⊸+) 3"),
    MatrixCase("⟜", "derived2", "after", "2 (+⟜{𝕩+1}) 3"),
    MatrixCase("⊘", "derived2", "valences", "2 (+⊘-) 3"),
    MatrixCase("◶", "derived2", "choose", "({2|𝕩}◶⟨{𝕩+10}⋄{𝕩+100}⟩) 3"),
    MatrixCase("⌾", "derived2", "under", "({𝕩+1}⌾-) 3"),
    MatrixCase("⎉", "derived2", "rank", "+´⎉1 (2‿3 ⥊ ↕6)"),
    MatrixCase("⚇", "derived2", "depth", "({𝕩+1}⚇1) ⟨1⋄2‿3⟩"),
    MatrixCase("⍟", "derived2", "repeat", "({𝕩+1}⍟2) 5"),
    MatrixCase("⎊", "derived2", "catch", "({𝕩+1}⎊{42˙}) 2"),
)

ALL_MATRIX_CASES = PRIMITIVE_MATRIX_CASES + MODIFIER_MATRIX_CASES
